version: "3"
services:
  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_BASE_API_URL=http://localhost:3030
    ports:
      - "3000:80"
  backend:
    env_file:
      - .env
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - "./uploads:/usr/src/app/uploads"
  postgres:
    image: "postgres:13"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
