version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_BASE_API_URL=http://localhost:3030
    ports:
      - "3000:80"
  backend:
    environment:
      NODE_ENV: production
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DATABASE: testing
      DATABASE_PORT: 5432
      PORT: 3030
    depends_on:
      - postgres
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - "./uploads:/usr/src/app/uploads"
  postgres:
    image: "postgres:13"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testing
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
